---
title: "칒velse_3_strings_logicals"
author: "Tobias Skj칝rlund"
date: "2024-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R 칒velse 3.0 Strings

Denne 칮velse handler om datatypen character


```{r}
# 1 Lav en variable der hedder navn der indeholder teksten "John"



# 2 Lav en variabel der hedder hobby som indeholder "Fugle"



# 3 Pr칮v at l칝gge navn og hobby sammen



# 4 lav en variabel der hedder s칝tning som indeholder en hel s칝tning



# Her er to variable K칮r linjerne:

z <- "1" 
x <- "1"

# 5 L칝g z og x sammen, hvad sker der og hvordan kan problemet l칮ses?
```

## R 칒velse 3.1 Strings 
Denne 칮velse bruger jeres egen data

Jeg har hentet jeres data fra datafilen for jer med f칮lgende kode:

# library(readxl)
# data_2024 <- read_xlsx('data/data_2024.xlsx')
# farve_2024 <- sort(unique(data_2024$farve))

I beh칮ver ikke g칮re det. :)

Herunder kan i se de forskellige input som I har skrevet: 

```{r}
# 6 Jeres yndlingsfarver fra 122 inputs, hvert unikke input er kun skrevet 1 gang:

farve_2024 <- c("#0041C2", "50% af alle farver", "All of them! (undtagen gr친. Men det er jo ikke en farve)", 
"bl친", "Bl친", "Bl친/Gr칮n", "Bl친/gul/lyser칮d", "Bl친?", "brun", 
"Cyan", "gr칮n", "Gr칮n", "Gr칮n selvf칮lgelig!", "Gr칮n:)", 
"Gul", "Guld", "Himmelbl친", "Indigo", "lilla", "Lilla", "Lysebl친", 
"lyser칮d", "Lyser칮d", "Lyser칮d游눘", "M칮rkebl친", "m칮rkebl친 eller bordeaux", 
"orange", "Orange", "Orange (like the sunset)", "r칮d", "R칮d", 
"sort", "Terracotta", "Turkis", "tyrkis")

# 7 Hvad er udfordringen ved at finde ud af hvilken farve flest bedst kan lide?


# 8 Ekstra opgave, hvis du har tid. Pr칮v at lav meningsfulde grupper fra jeres data. Ved at bruge funktionen c() som vi kommer tilbage til

gr칮n <- c("gr칮n","Gr칮n","Gr칮n selvf칮lgelig!","Gr칮n:)")
# bl친 <- c()
# osv.

# Hvad er udfordringen ved dette?

```

## R 칒velse 3.2 Logicals/Booleans

```{r}
# Logicals har en v칝rdi FALSE = 0 TRUE = 1 

# 9 Pr칮v at l칝gge TRUE sammen med TRUE

# 10 Pr칮v TRUE+TRUE+FALSE

# 11 Her er jeres svar p친 sp칮rgsm친let: Er Danmark et gr칮nt foregangsland?

dk_gr칮n <- c(FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, 
TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, 
TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, 
TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 
FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, 
TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, 
FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, 
FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, 
TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, 
TRUE, TRUE, FALSE, FALSE)

# 12 Pr칮v at bruge funktionen: sum() p친 objektet dk_gr칮n for at se hvor mange der har svaret Sandt til sp칮rgsm친let.


# 13 Pr칮v at bruge funktionen length() p친 dk_gr칮n for at se hvor mange svar der er i alt


# 14 Er der flest der har svaret sandt eller falskt?


# 15 Ekstra opgave hvis du har tid. mean() funktionen giver gennemsnittet. Hvordan kan outputtet tolkes hvis mean() tages af dk_gr칮n

```





