---
title: "Øvelse 2 - variable"
output:
  html_document:
    df_print: paged
---

## Øvelse 2.1 Hashtags

Formålet med øvelsen er at køre kodeblokken.

Tryk på den grønne pil til højre eller marker linjer og tryk ctrl + enter

```{r}
# Marker en eller flere linjer 
# Fjern hastags fra de 3 linjer der har kode herunder:

# 2+2
# 10*10
# 5+5

# Sæt hastags ved at markere alle tre linjer og tryk ctrl + shift + c

# Denne linje skal have hashtag
# Denne linje skal have hashtag
# Denne linje skal have hashtag
```

## Øvelse 2.2 Variable

Læg mærke til environment vinduet

Værdier tilføjes til variable med <-

eks: x <- 10

```{r}
# 1 lav en variabel z med værdien 20


# 2 skift værdien for z til 50


# 3 Gang z med 2


# 4 lav en ny variabel der hedder ny_variabel med værdien 10


# 5 Sæt z til at have den værdi, der er gemt i ny_variabel


# 6 Lav en ny variabel der hedder NY_VARIABEL med værdien 25


# 7 Læg z + ny_variabel + NY_VARIABEL sammen


# 8 Tag kvadratroden sqrt() af z


# 9 gem kvadratroden af z i en variabel der hedder kvadratrod_z


# 10 udregn z kun ved at bruge kvadratrod_z 


# 11 ekstra prøv at lave 2 variable med samme værdi men forskelligt navn på en linje kode.


```


